Token Code: 2
Token Value: ImyFunction
Token Code: 5
Token Code: 2
Token Value: Ia1
Token Code: 7
Token Code: 2
Token Value: Ia2
Token Code: 6
Token Code: 3
Token Code: 2
Token Value: Ivar1
Token Code: 9
Token Value: L34
Token Code: 8
Token Code: 2
Token Value: Ivar2
Token Code: 9
Token Value: L43
Token Code: 8
Token Code: 2
Token Value: Ivar3
Token Code: 9
Token Value: Ivar1
Token Code: 16
Token Value: Ivar2
Token Code: 8
Token Code: 2
Token Value: Ivar4
Token Code: 9
Token Value: Ivar2
Token Code: 14
Token Value: Ivar1
Token Code: 8
Token Code: 2
Token Value: Ivar5
Token Code: 9
Token Value: Ivar4
Token Code: 15
Token Value: Ivar3
Token Code: 8
Token Code: 2
Token Value: Ivar6
Token Code: 9
Token Value: Ivar1
Token Code: 12
Token Value: Ivar5
Token Code: 8
Token Code: 1
Token Value: Ivar3
Token Code: 8
Token Code: 4
Token Code: 2
Token Value: Imain
Token Code: 5
Token Code: 2
Token Value: Iarg1
Token Code: 7
Token Code: 2
Token Value: Iarg2
Token Code: 7
Token Code: 2
Token Value: Iarg3
Token Code: 6
Token Code: 3
Token Code: 2
Token Value: Ivar1
Token Code: 9
Token Value: Iarg1
Token Code: 18
Token Value: Iarg2
Token Code: 8
Token Code: 2
Token Value: Ivar2
Token Code: 9
Token Value: ImyFunction
Token Code: 5
Token Value: Ivar1
Token Code: 7
Token Value: L5
Token Code: 6
Token Code: 8
Token Code: 2
Token Value: Ivar1234
Token Code: 9
Token Value: Ivar2
Token Code: 11
Token Value: L12
Token Code: 8
Token Code: 1
Token Value: Ivar1
Token Code: 13
Token Value: Ivar2
Token Code: 8
Token Code: 4
