Token Code: 2
Token Value: ImyFunction
Token Code: 5
Token Code: 6
Token Code: 3
Token Code: 2
Token Value: Ivar1
Token Code: 9
Token Value: L34
Token Code: 8
Token Code: 2
Token Value: Ivar2
Token Code: 9
Token Value: L43
Token Code: 8
Token Code: 2
Token Value: Ivar3
Token Code: 9
Token Value: Ivar1
Token Code: 10
Token Value: Ivar2
Token Code: 8
Token Code: 1
Token Value: Ivar3
Token Code: 8
Token Code: 4
Token Code: 2
Token Value: Imain
Token Code: 5
Token Code: 2
Token Value: Iarg1
Token Code: 7
Token Code: 2
Token Value: Iarg2
Token Code: 6
Token Code: 3
Token Code: 2
Token Value: Ivar1
Token Code: 9
Token Value: Iarg1
Token Code: 10
Token Value: Iarg2
Token Code: 8
Token Code: 2
Token Value: Ivar2
Token Code: 9
Token Value: ImyFunction
Token Code: 5
Token Code: 6
Token Code: 8
Token Code: 1
Token Value: Ivar1
Token Code: 12
Token Value: Ivar2
Token Code: 8
Token Code: 4
